version: "2"

volumes:
  orderer0.example.com:
  orderer4.example.com:
  orderer1.example.com:
  peer0.org1.example.com:

networks:
    behave:

services:
    peer0.org1.example.com:
        extends:
            file: docker-compose-base.yml
            service: peer
        container_name: peer0.org1.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
            - CORE_PEER_ID=peer0.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER0_ORG1}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER0_ORG1}
            - CORE_PEER_LOCALMSPID=Org1MSP
            - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org1.example.com/tls/ca.crt
            - CORE_PEER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org1.example.com/tls/client.crt
            - CORE_PEER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org1.example.com/tls/client.key
        volumes:
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/tls
            - ../crypto-config/peerOrganizations/org1.example.com/users:/var/hyperledger/users
            - ../network-config/:/var/hyperledger/configs
            - peer0.org1.example.com:/var/hyperledger/production
        extra_hosts:
            - "peer0.org2.example.com:${HOST_B}"
            - "orderer1.example.com:${HOST_B}"
            - "ca.org2.example.com:${HOST_B}"
            - "peer0.org3.example.com:${HOST_C}"
            - "orderer2.example.com:${HOST_C}"
            - "ca.org3.example.com:${HOST_C}"
            - "peer0.org4.example.com:${HOST_D}"
            - "orderer3.example.com:${HOST_D}"
            - "ca.org4.example.com:${HOST_D}"

        networks:
            behave:
                aliases:
                    - ${CORE_PEER_NETWORKID}
        ports:
            - 7051:7051
            - 7053:7053

    orderer0.example.com:
        extends:
            file: docker-compose-base.yml
            service: orderer
        container_name: orderer0.example.com
        environment:
            - ORDERER_HOST=orderer0.example.com
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
        extra_hosts:
            - "peer0.org2.example.com:${HOST_B}"
            - "orderer1.example.com:${HOST_B}"
            - "ca.org2.example.com:${HOST_B}"
            - "peer0.org3.example.com:${HOST_C}"
            - "orderer2.example.com:${HOST_C}"
            - "ca.org3.example.com:${HOST_C}"
            - "peer0.org4.example.com:${HOST_D}"
            - "orderer3.example.com:${HOST_D}"
            - "ca.org4.example.com:${HOST_D}"


        volumes:
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls:/var/hyperledger/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer0.example.com:/var/hyperledger/production/orderer

        networks:
            behave:
                aliases:
                    - ${CORE_PEER_NETWORKID}
        ports:
            - 7050:7050

    orderer1.example.com:
        extends:
            file: docker-compose-base.yml
            service: orderer
        container_name: orderer1.example.com
        environment:
            - ORDERER_HOST=orderer1.example.com
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
        extra_hosts:
            - "peer0.org2.example.com:${HOST_B}"
            - "orderer1.example.com:${HOST_B}"
            - "ca.org2.example.com:${HOST_B}"
            - "peer0.org3.example.com:${HOST_C}"
            - "orderer2.example.com:${HOST_C}"
            - "ca.org3.example.com:${HOST_C}"
            - "peer0.org4.example.com:${HOST_D}"
            - "orderer3.example.com:${HOST_D}"
            - "ca.org4.example.com:${HOST_D}"

        volumes:
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/tls:/var/hyperledger/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer1.example.com:/var/hyperledger/production/orderer

        networks:
            behave:
                aliases:
                    - ${CORE_PEER_NETWORKID}
        ports:
            - 8050:7050

    orderer4.example.com:
        extends:
            file: docker-compose-base.yml
            service: orderer
        container_name: orderer4.example.com
        environment:
            - ORDERER_HOST=orderer4.example.com
            - ORDERER_ABSOLUTEMAXBYTES=${ORDERER_ABSOLUTEMAXBYTES}
            - ORDERER_PREFERREDMAXBYTES=${ORDERER_PREFERREDMAXBYTES}
        extra_hosts:
            - "peer0.org2.example.com:${HOST_B}"
            - "orderer1.example.com:${HOST_B}"
            - "ca.org2.example.com:${HOST_B}"
            - "peer0.org3.example.com:${HOST_C}"
            - "orderer2.example.com:${HOST_C}"
            - "ca.org3.example.com:${HOST_C}"
            - "peer0.org4.example.com:${HOST_D}"
            - "orderer3.example.com:${HOST_D}"
            - "ca.org4.example.com:${HOST_D}"

        volumes:
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/msp:/var/hyperledger/msp
            - ../crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls:/var/hyperledger/tls
            - ../network-config/:/var/hyperledger/configs
            - orderer4.example.com:/var/hyperledger/production/orderer

        networks:
            behave:
                aliases:
                    - ${CORE_PEER_NETWORKID}
        ports:
            - 9050:7050

    ca.org1.example.com:
        image: hyperledger/fabric-ca:1.4.9
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/be500145c4efafd6566445c65894664d6486c5e3d0be26a81b646560d10e96be_sk
        extra_hosts:
            - "peer0.org2.example.com:${HOST_B}"
            - "orderer1.example.com:${HOST_B}"
            - "ca.org2.example.com:${HOST_B}"
            - "peer0.org3.example.com:${HOST_C}"
            - "orderer2.example.com:${HOST_C}"
            - "ca.org3.example.com:${HOST_C}"
            - "peer0.org4.example.com:${HOST_D}"
            - "orderer3.example.com:${HOST_D}"
            - "ca.org4.example.com:${HOST_D}"
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start -b admin:adminpw'
        volumes:
            - ../crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
            - ../fabric-ca-db/org1/:/etc/hyperledger/fabric-ca-server
        container_name: ca.org1.example.com
        networks:
            behave:
                aliases:
                    - ${CORE_PEER_NETWORKID}
